site_name: Peltomappi
site_url: https://gispocoding.github.io/eip-peltomappi/
copyright: 'Tekijä: <a href="info@gispo.fi">Gispo Suomi Oy</a>'
nav:
  - Koti: index.md
  - Esittely: esittely.md
  - Projektin lataaminen: projektin_lataaminen.md
  - Karttanäkymä: karttanäkymä.md
  - Selainkäyttöliittymä: selainkayttoliittyma.md
  - Kohteen lisääminen: kohteen_lisääminen.md
  - Alueen lisääminen ja jakaminen: alueen_lisääminen.md
  - Penetrometri: penetrometri.md
  - MARA-kuoppa: mara_kuoppa.md
  - Peltolohkon yhteenveto: peltolohkon_yhteenveto.md
  - Salaojakarttojen georeferointi: salaojakarttojen_georeferointi.md
  - Reitin nauhoitus: reitin_nauhoitus.md
  - Muut ominaisuudet: muut_ominaisuudet.md
  - Palaute: palaute.md
  - Muutosloki: muutosloki.md

use_directory_urls: false

markdown_extensions:
  - footnotes
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - toc:
      toc_depth: 2

theme:
  name: material
  language: fi
  custom_dir: docs/overrides
  features:
    - navigation.footer
    - navigation.instant
    - navigation.instant.progress
    - toc.integrate
    - search.suggest
    - search.highlight
    - header.autohide
    - content.code.copy
  palette:
    scheme: peltomappi
  logo: img/pysty_peltomappi.png
  favicon: img/pysty_peltomappi.png



plugins:
  - redirects:
      redirect_maps:
        '8_saadata.md': 'saadata.md'
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: false
  - glightbox
extra_css:
  - stylesheets/extra.css
